// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: passport_issuance.proto

package passportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PassportIssuanceService_IssuePassport_FullMethodName    = "/are.passport.v1.PassportIssuanceService/IssuePassport"
	PassportIssuanceService_GetPassport_FullMethodName      = "/are.passport.v1.PassportIssuanceService/GetPassport"
	PassportIssuanceService_GetAgentPassport_FullMethodName = "/are.passport.v1.PassportIssuanceService/GetAgentPassport"
	PassportIssuanceService_VerifyPassport_FullMethodName   = "/are.passport.v1.PassportIssuanceService/VerifyPassport"
	PassportIssuanceService_RenewPassport_FullMethodName    = "/are.passport.v1.PassportIssuanceService/RenewPassport"
	PassportIssuanceService_RevokePassport_FullMethodName   = "/are.passport.v1.PassportIssuanceService/RevokePassport"
	PassportIssuanceService_ListPassports_FullMethodName    = "/are.passport.v1.PassportIssuanceService/ListPassports"
)

// PassportIssuanceServiceClient is the client API for PassportIssuanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassportIssuanceServiceClient interface {
	IssuePassport(ctx context.Context, in *IssuePassportRequest, opts ...grpc.CallOption) (*IssuePassportResponse, error)
	GetPassport(ctx context.Context, in *GetPassportRequest, opts ...grpc.CallOption) (*GetPassportResponse, error)
	GetAgentPassport(ctx context.Context, in *GetAgentPassportRequest, opts ...grpc.CallOption) (*GetAgentPassportResponse, error)
	VerifyPassport(ctx context.Context, in *VerifyPassportRequest, opts ...grpc.CallOption) (*VerifyPassportResponse, error)
	RenewPassport(ctx context.Context, in *RenewPassportRequest, opts ...grpc.CallOption) (*RenewPassportResponse, error)
	RevokePassport(ctx context.Context, in *RevokePassportRequest, opts ...grpc.CallOption) (*RevokePassportResponse, error)
	ListPassports(ctx context.Context, in *ListPassportsRequest, opts ...grpc.CallOption) (*ListPassportsResponse, error)
}

type passportIssuanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassportIssuanceServiceClient(cc grpc.ClientConnInterface) PassportIssuanceServiceClient {
	return &passportIssuanceServiceClient{cc}
}

func (c *passportIssuanceServiceClient) IssuePassport(ctx context.Context, in *IssuePassportRequest, opts ...grpc.CallOption) (*IssuePassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_IssuePassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) GetPassport(ctx context.Context, in *GetPassportRequest, opts ...grpc.CallOption) (*GetPassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_GetPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) GetAgentPassport(ctx context.Context, in *GetAgentPassportRequest, opts ...grpc.CallOption) (*GetAgentPassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentPassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_GetAgentPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) VerifyPassport(ctx context.Context, in *VerifyPassportRequest, opts ...grpc.CallOption) (*VerifyPassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_VerifyPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) RenewPassport(ctx context.Context, in *RenewPassportRequest, opts ...grpc.CallOption) (*RenewPassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewPassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_RenewPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) RevokePassport(ctx context.Context, in *RevokePassportRequest, opts ...grpc.CallOption) (*RevokePassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokePassportResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_RevokePassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passportIssuanceServiceClient) ListPassports(ctx context.Context, in *ListPassportsRequest, opts ...grpc.CallOption) (*ListPassportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPassportsResponse)
	err := c.cc.Invoke(ctx, PassportIssuanceService_ListPassports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassportIssuanceServiceServer is the server API for PassportIssuanceService service.
// All implementations must embed UnimplementedPassportIssuanceServiceServer
// for forward compatibility.
type PassportIssuanceServiceServer interface {
	IssuePassport(context.Context, *IssuePassportRequest) (*IssuePassportResponse, error)
	GetPassport(context.Context, *GetPassportRequest) (*GetPassportResponse, error)
	GetAgentPassport(context.Context, *GetAgentPassportRequest) (*GetAgentPassportResponse, error)
	VerifyPassport(context.Context, *VerifyPassportRequest) (*VerifyPassportResponse, error)
	RenewPassport(context.Context, *RenewPassportRequest) (*RenewPassportResponse, error)
	RevokePassport(context.Context, *RevokePassportRequest) (*RevokePassportResponse, error)
	ListPassports(context.Context, *ListPassportsRequest) (*ListPassportsResponse, error)
	mustEmbedUnimplementedPassportIssuanceServiceServer()
}

// UnimplementedPassportIssuanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPassportIssuanceServiceServer struct{}

func (UnimplementedPassportIssuanceServiceServer) IssuePassport(context.Context, *IssuePassportRequest) (*IssuePassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) GetPassport(context.Context, *GetPassportRequest) (*GetPassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) GetAgentPassport(context.Context, *GetAgentPassportRequest) (*GetAgentPassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentPassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) VerifyPassport(context.Context, *VerifyPassportRequest) (*VerifyPassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) RenewPassport(context.Context, *RenewPassportRequest) (*RenewPassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewPassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) RevokePassport(context.Context, *RevokePassportRequest) (*RevokePassportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokePassport not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) ListPassports(context.Context, *ListPassportsRequest) (*ListPassportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPassports not implemented")
}
func (UnimplementedPassportIssuanceServiceServer) mustEmbedUnimplementedPassportIssuanceServiceServer() {
}
func (UnimplementedPassportIssuanceServiceServer) testEmbeddedByValue() {}

// UnsafePassportIssuanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassportIssuanceServiceServer will
// result in compilation errors.
type UnsafePassportIssuanceServiceServer interface {
	mustEmbedUnimplementedPassportIssuanceServiceServer()
}

func RegisterPassportIssuanceServiceServer(s grpc.ServiceRegistrar, srv PassportIssuanceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPassportIssuanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PassportIssuanceService_ServiceDesc, srv)
}

func _PassportIssuanceService_IssuePassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).IssuePassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_IssuePassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).IssuePassport(ctx, req.(*IssuePassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_GetPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).GetPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_GetPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).GetPassport(ctx, req.(*GetPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_GetAgentPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).GetAgentPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_GetAgentPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).GetAgentPassport(ctx, req.(*GetAgentPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_VerifyPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).VerifyPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_VerifyPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).VerifyPassport(ctx, req.(*VerifyPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_RenewPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).RenewPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_RenewPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).RenewPassport(ctx, req.(*RenewPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_RevokePassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).RevokePassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_RevokePassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).RevokePassport(ctx, req.(*RevokePassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassportIssuanceService_ListPassports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPassportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassportIssuanceServiceServer).ListPassports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassportIssuanceService_ListPassports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassportIssuanceServiceServer).ListPassports(ctx, req.(*ListPassportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassportIssuanceService_ServiceDesc is the grpc.ServiceDesc for PassportIssuanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassportIssuanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "are.passport.v1.PassportIssuanceService",
	HandlerType: (*PassportIssuanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssuePassport",
			Handler:    _PassportIssuanceService_IssuePassport_Handler,
		},
		{
			MethodName: "GetPassport",
			Handler:    _PassportIssuanceService_GetPassport_Handler,
		},
		{
			MethodName: "GetAgentPassport",
			Handler:    _PassportIssuanceService_GetAgentPassport_Handler,
		},
		{
			MethodName: "VerifyPassport",
			Handler:    _PassportIssuanceService_VerifyPassport_Handler,
		},
		{
			MethodName: "RenewPassport",
			Handler:    _PassportIssuanceService_RenewPassport_Handler,
		},
		{
			MethodName: "RevokePassport",
			Handler:    _PassportIssuanceService_RevokePassport_Handler,
		},
		{
			MethodName: "ListPassports",
			Handler:    _PassportIssuanceService_ListPassports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passport_issuance.proto",
}
